开发cli 


不能够不处理，也不能够吃掉错误  


操作错误与编码错误   

目的明确了，才能够使  

![](/blog_assets/error_handle.png)   


确保每一个函数的功能与职责是单一的  


明确错误类型  



#### 如何处理  

明确错误类型之后，类型明确，则直接处理。若不明确，那就传递这个错误。    

程序错误，就直接崩溃  

#### 抛出内容
错误的调用栈
与本次错误相关的上下文，比如几个关键变量的值   
若是决定不直接展示错误的内容，则可以为客户提供一个错误的编号，以便事后反馈可以还原当时现场。   

通常向一个node端的server请求http服务的时候，既没有收到成功响应，也没有收到失败响应，一直保持着链接，通常是因为server端代码抛出了错误但没有正常的进行捕获，导致这个请求的处理流被意外地中断掉了。   

### 错误（Error） 与 异常(Exception)


异常分为两种  
##### 预期的异常
> 参数的不合法，前提条件不满足（开发人员能够猜到的可能发生的错误）

处理的时候，我们一般会把预期的异常，直接进行抛出，从而达到通知外层调用者的作用。   

##### 非预期的异常
> Javascript引擎的运行时异常  (开发人员你无法预期到的。比如，调用数据库或者读文件过程总发生的内部错误) ，一般这些错误是严重错误，会引起程序崩溃那种。   

非预期的错误，一般是由于我们开发人员(库开发人员，而不是调用人员)的编程错误，又或者是再底层的依赖库的错误，对于这样的错误，我们作为库开发人员，应该优先捕捉这些错误，然后再转化为预期的异常，再向外抛出。 


#### 传递错误   
我们可能在某一层级没有足够的信息去决定如何处理这个错误，例如在Data Access层，一个数据库查询发生了错误，在Data Access这一层并不知道该错误对于上层业务逻辑来说意味着什么，而仅仅知道这个查询失败了。   

所以要建立一种机制，将错误不断向上层传递，知道达到某个层级，有足够的信息去决定如何处理这个错误。    

一个异常若被catch了，便不会再继续回溯了，这时候我们称这个异常被处理了。   


使用同步 throw Error  

异步处理： 在callback内部，回调值  
```js
function（err,result){
     // 注意第一个函数通常就是错误体本身   
}
``` 
使用 EventEmitter 去暴露错误。   

#### 实战中如何操作  
1️⃣ 使用typescript去提前检查出来低级错误。 
2️⃣ 使用async/await去表示异步代码，try catch基本就是同步的思想。  



finally语句中的代码，会忽略try和catch中的return语句，不受其约束，而始终执行。


